name: CD for Laravel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t nhatminh2005/laravel-app:latest .

      - name: Push Docker image
        run: docker push nhatminh2005/laravel-app:latest

      # - name: Trigger Deploy on VPS
      #   run: |
      #     curl -X POST http://your-vps-domain.com/deploy \
      #          -H "Authorization: Bearer ${{ secrets.VPS_DEPLOY_KEY }}"
